language: python
python:
 - 2.7
install:
  - ./.travis_setup
env:
  - SKIP_COVERAGE=1 SKIP_INSTALL=1
script: fab test
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#armstrongcms"
